### ISSUE TITLE
Use PSR

### ISSUE THREAD

**Issue by vyuldashev** [crisp-im/php-crisp-api#1]
Hello there,

great product, but quickly going through the code I suggest to use PSR.

**Comment by baptistejamin** [comment]
I can be done. PHP is not our main language and we don't use it in production. Do you have any ressource or example?

**Comment by vyuldashev** [comment]
http://www.php-fig.org/psr/

**Comment by baptistejamin** [comment]
Haha, I can Google it too ;)

Now, my question is more about a famous PSR project on GitHub. 
Your project https://github.com/vladimir-yuldashev/creditpilot is PSR?

**Comment by vyuldashev** [comment]
Use https://github.com/laravel/framework as a better example.

**Comment by eliottvincent** [comment]
Fixed with 1ffc8dd135e66f16965cd2ab5317297c3c1f6d9b.
