### ISSUE TITLE
Unable to invite an operator to a website

### ISSUE THREAD

**Issue by rmilesson** [crisp-im/php-crisp-api#11]
It's currently not possible to invite an operator to a website since `WebsiteOperators::createOne` requires `operatorId` as an argument. This `operatorId` has not yet been created.

This does not match the API as defined in https://docs.crisp.chat/api/v1/#website-website-operator-post

**Comment by valeriansaliou** [comment]
Thanks. This method should not have been added to the PHP library, as it's an internal route that's not documented for public access. I've removed it from the PHP library in ef00c5419e9737e673f956f35439a6a802133892
