### ISSUE TITLE
It's not possible to delete website with this wrapper

### ISSUE THREAD

**Issue by rmilesson** [crisp-im/php-crisp-api#12]
Hi!

It's not possible to delete a website with this API wrapper as of now since the verify-parameter is not passed along to the API.

Error message when using `CrispWebsite::delete`:

```
{"error":true,"reason":"invalid_data","data":{"namespace":"data","message":"data should have required property 'verify'"}}
```

**Comment by eliottvincent** [comment]
Hello, the error comes from the fact that the endpoint expects the `verify` parameter (your password) in `data`, in order to correctly process the deletion.
