### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by JulienBrochier** [crisp-im/php-crisp-api#14]
Hi,
I've added this code to my website : 

> require __DIR__ . '/vendor/autoload.php';
> $CrispClient = new Crisp();
> 
> $CrispClient->authenticate(identifier, key);
> 
> $profile = $CrispClient->userProfile->get();
> $firstName = $profile["first_name"];
> echo "Hello $firstName";

with my own identifier and key and it returns a 500 error.

In particular, this line : `$profile = $CrispClient->userProfile->get()`  seems to cause the issue.

 I've also tried to create a conversation and I have the same issue

**Comment by eliottvincent** [comment]
Hello Julien! I can't seem to reproduce. Please feel free to re-open this issue if you still encounter any error again.
