### ISSUE TITLE
Allow filtering data in getList()

### ISSUE THREAD

**Issue by leo-unglaub** [crisp-im/php-crisp-api#15]
Hey,
i am working on a little cli script that automates some tasks for a customer of mine and it would be very useful if i could supply filters as a third argument on the `CrispClient->websiteConversations->getList(websiteId, page)` function. That way we could only get the data we need from the server and did not have to pull down all the data all the time. This would also be good for you, because it would greatly reduce the number of API requests send to your server. 

Thanks and greetings
Leo

**Comment by leo-unglaub** [comment]
According to this document here (https://docs.crisp.chat/api/v1/#website-website-conversations-get) there is already logic in place to filter requests, but its not possible to pass it to the function.

**Comment by valeriansaliou** [comment]
@baptistejamin
