### ISSUE TITLE
API returns wrong data

### ISSUE THREAD

**Issue by leo-unglaub** [crisp-im/php-crisp-api#16]
Hey,
i have a little cli script that just calls the getList() method and prints out every ID on a single row. I executed the script 7 times with 10 second delays during each execution and i get totally different results. During the time no new conversations where started on the website, nothing changed. But the API returned complete different results. 

```
$ crisp-list-conversations | wc -l
144

$ crisp-list-conversations | wc -l
143

$ crisp-list-conversations | wc -l
122

$ crisp-list-conversations | wc -l
75

$ crisp-list-conversations | wc -l
57

$ crisp-list-conversations | wc -l
77

$ crisp-list-conversations | wc -l
47
```

As you can see the lines of results differ completely. I asume that you cache the requests somewhere and depending on what edge node serves the request i get a different response.

Could you please be so kind and look into this. That would help alot!
Thanks and greetings
Leo

**Comment by leo-unglaub** [comment]
I just executed the same script at the same time on two different laptops. One of them was in a different network, so we came from different IP addresses. I got very different results back from the API for the same call at the same time.

**Comment by eliottvincent** [comment]
Closing (inactive).
