### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by jbarmanet** [crisp-im/php-crisp-api#17]
Just to let you know a typo, the `peopleId` param should not be here:

**List People Profiles:** `CrispClient->websitePeople->listPeopleProfiles(websiteId, peopleId, page)`

should be

**List People Profiles:** `CrispClient->websitePeople->listPeopleProfiles(websiteId, page)`

**Comment by eliottvincent** [comment]
Closed with https://github.com/crisp-im/php-crisp-api/commit/b18ae793a6d8a2c004e2aa23265aea439b153540, thanks!
