### ISSUE TITLE
Where is vendor/autoload.php?

### ISSUE THREAD

**Issue by rvencu** [crisp-im/php-crisp-api#6]
I guess because I cannot find the vendor/autoload.php file I have no reference to the RestClient class

`$this->_rest = new RestClient`

**Comment by rvencu** [comment]
well, composer only stuff. Downloading the zip file is not enough

**Comment by baptistejamin** [comment]
Could you contact us on crisp.chat ? It seems to be related with how you are using the SDK itself.

Did you install composer ?

**Comment by rvencu** [comment]
Yes, I am in contact via chat. I use PHPStorm on my Window 10. I have a linux server on backend, I just went there, ran the composer commands then downloaded all files into my project. Apparently it should work now still I was not yet able to test the first sample bot (the advanced one from example folder). I will be on chat if I will be totally stuck with it.

**Comment by baptistejamin** [comment]
Please contact us on crisp.chat. Ask Baptiste.
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 8 Aug 2018, at 13:41, Richard Vencu <notifications@github.com> wrote:

Yes, I am in contact via chat. I use PHPStorm on my Window 10. I have a linux server on backend, I just went there, ran the composer commands then downloaded all files into my project. Apparently it should work now still I was not yet able to test the first sample bot (the advanced one from example folder). I will be on chat if I will be totally stuck with it.

**Comment by rvencu** [comment]
All is working well now. Setting up composer commands properly solved any missing dependency
